export enum BookingStatus {
  PENDING = "PENDING",

  CONFIRMED = "CONFIRMED",

  PROVIDER_ASSIGNED = "PROVIDER_ASSIGNED",

  PROVIDER_ACCEPTED = "PROVIDER_ACCEPTED",

  PROVIDER_REJECTED = "PROVIDER_REJECTED",

  ON_THE_WAY = "ON_THE_WAY",

  ARRIVED = "ARRIVED",
  WORKING = "WORKING",

  STARTED = "STARTED",

  COMPLETED = "COMPLETED",

  CANCELLED = "CANCELLED",
}