// export enum NotificationType {
//   NEW_BOOKING = "NEW_BOOKING",

//   BOOKING_ASSIGNED = "BOOKING_ASSIGNED",

//   BOOKING_ACCEPTED = "BOOKING_ACCEPTED",

//   BOOKING_REJECTED = "BOOKING_REJECTED",

//   PROVIDER_ON_THE_WAY = "PROVIDER_ON_THE_WAY",

//   PROVIDER_ARRIVED = "PROVIDER_ARRIVED",

//   JOB_STARTED = "JOB_STARTED",

//   JOB_COMPLETED = "JOB_COMPLETED",

//   PAYMENT_SUCCESS = "PAYMENT_SUCCESS",

//   PAYMENT_FAILED = "PAYMENT_FAILED",

//   NEW_REVIEW = "NEW_REVIEW",

//   ADMIN_ALERT = "ADMIN_ALERT",
// }

export enum NotificationType {
  // Booking
  NEW_BOOKING = "NEW_BOOKING",
  BOOKING_ASSIGNED = "BOOKING_ASSIGNED",
  BOOKING_ACCEPTED = "BOOKING_ACCEPTED",
  BOOKING_REJECTED = "BOOKING_REJECTED",

  // Provider journey
  PROVIDER_ON_THE_WAY = "PROVIDER_ON_THE_WAY",
  PROVIDER_ARRIVED = "PROVIDER_ARRIVED",

  // Service
  JOB_STARTED = "JOB_STARTED",
  JOB_COMPLETED = "JOB_COMPLETED",

  // Payment
  PAYMENT_SUCCESS = "PAYMENT_SUCCESS",
  PAYMENT_FAILED = "PAYMENT_FAILED",

  // Review
  NEW_REVIEW = "NEW_REVIEW",

  // Admin
  ADMIN_ALERT = "ADMIN_ALERT",

  // Additional recommended events
  BOOKING_CANCELLED = "BOOKING_CANCELLED",
  BOOKING_RESCHEDULED = "BOOKING_RESCHEDULED",
  PROVIDER_REASSIGNED = "PROVIDER_REASSIGNED",
  BOOKING_REMINDER = "BOOKING_REMINDER",
}